version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mygym
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  
  myapp:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db:
