version: '3.8'
services:
    mysql:
      image: mysql:latest
      ports:
      - "3306:3306"
      environment:
      - MYSQL_INITDB_ROOT_USERNAME: root
      - MYSQL_INITDB_ROOT_PASSWORD: root
      - MYSQL_DB_NAME: mygym
      volumes:
      - ./db-data:/var/lib/mysql
    
    mygym:
      image: mygym-docker:latest
      depends_on:
      - mysql
      build: "./"
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mygym
        - SPRING_DATASOURCE_USERNAME: root
        - SPRING_DATASOURCE_PASSWORD: root
        - SPRING_JPA_HIBERNATE_DDL_AUTO: create
      volumes:
        - ./app-data:/app
      command: sh -c "cd /app && ./mvnw spring-boot:run"

